export enum StatusIdHistoricoAlteracaoPerfilInvestimentoEnum {
  SOLICITACAO_PROCESSADA = '1',
  CANCELADO_NOVA_SOLICITACAO_REGISTRADA = '2',
  CANCELADO_POR_SOLICITACAO_DO_PARTICIPANTE = '3',
  CONFIRMACAO_PENDENTE = '4',
  FORMULARIO_FISICO = '5',
  SOLICITACAO_RECEBIDA = '6',
  ERRO_NO_PROCESSAMENTO = '7'
}
