export enum PlanoSituacaoEnum {
  PATROCINADO = 'PATROCINADO',
  AUTOPATROCINADO = 'AUTOPATROCINADO',
  VINCULADO = 'VINCULADO',
  BPD_SALDO = 'BPD - SALDO',
  BPD_DEPOSITO = 'BPD - DEPOSITO',
  SITUACAO_PATROCINADO_CJ = 'PATROCINADO - CJ/CC/FC',
  ASSISTIDO = 'ASSISTIDO'
}
